import type { ReportRange } from "@/presentation/types/reports";

export const RANGE_OPTIONS: Array<{ value: ReportRange; label: string }> = [
  { value: "7d", label: "7 أيام" },
  { value: "30d", label: "30 يوماً" },
  { value: "90d", label: "90 يوماً" },
  { value: "all", label: "الكل" }
];

export const COPY = {
  title: "إحصاءات بصمات",
  loadingHint: "جاري جمع مؤشرات المبادرة...",
  errorTitle: "تعذر تحميل الإحصائيات",
  errorMessage: "لم نتمكن من قراءة البيانات حالياً. يمكنك إعادة المحاولة دون فقدان مسار الصفحة.",
  retry: "إعادة المحاولة",
  staleError: "آخر تحديث فشل. الأرقام الظاهرة هي آخر قراءة ناجحة.",
  rangeAria: "الفترة الزمنية",
  fullRange: "الفترة الكاملة",
  vsPrevious: "عن السابقة",
  emptyChart: "لا تتوافر بيانات لهذا الرسم بعد",
  emptyDaily: "لم يُسجل أي متطوعين أو طلبات انضمام خلال هذه الأيام",
  emptyMeetings: "لا توجد أنشطة مرتبطة باجتماع بعد",
  emptyMatch: "لا توجد أسماء اجتماعات للمطابقة بعد",
  emptySystem: "لا توجد عمليات نظام خلال هذه الفترة",
  pulse: {
    volunteers: "متطوعون جدد",
    activities: "أنشطة أضيفت",
    requests: "طلبات انضمام",
    hours: "ساعات مسجلة",
    certificates: "شهادات مكتملة",
    attendance: "نسبة الحضور"
  },
  totals: {
    volunteers: "المتطوعون",
    activities: "الأنشطة",
    pending: "طلبات معلّقة",
    hours: "إجمالي الساعات",
    certificates: "شهادات مكتملة",
    thisMonth: "متطوعو هذا الشهر"
  },
  panels: {
    daily: "النشاط اليومي",
    dailySub: (days: string) => `المتطوعون الجدد وطلبات الانضمام - آخر ${days} أيام`,
    recentDays: "آخر 8 أيام",
    recentDaysSub: "مقارنة المتطوعين الجدد بطلبات الانضمام",
    conversion: "مؤشرات التحويل الأسبوعية",
    conversionSub: "طلبات الانضمام والمتطوعون الجدد مرتبة من السبت إلى الجمعة",
    journey: "من الطلب إلى الحضور",
    journeySub: "عدد الطلبات في كل مرحلة: طلب، قبول، ثم حضور",
    outcomes: "نتيجة طلبات الانضمام",
    outcomesSub: "مقبولة، مرفوضة، معلّقة، أو ملغاة خلال الفترة",
    gender: "صورة المتطوعين",
    genderSub: "توزيع المتطوعين حسب الجنس",
    ages: "الفئات العمرية",
    agesSub: "توزيع المتطوعين حسب الفئة العمرية",
    cityAge: "الفئات العمرية حسب المدينة",
    cityAgeSub: "اختر فئة عمرية لعرض عدد المتطوعين في كل مدينة",
    education: "المستوى التعليمي",
    educationSub: "توزيع المتطوعين حسب المستوى التعليمي",
    cities: "المدن الأكثر نشاطاً",
    citiesSub: "حسب مدينة إقامة المتطوعين",
    activityStatus: "حالة الأنشطة",
    activityStatusSub: "توزيع الأنشطة حسب حالتها الحالية",
    activityType: "نوع النشاط",
    activityTypeSub: "وجاهي مقابل إلكتروني",
    attendance: "سجل الحضور والغياب",
    attendanceSub: "المتطوعون الذين سُجل حضورهم أو غيابهم خلال هذه الفترة",
    content: "المحتوى",
    contentSub: "المجموع حتى الآن",
    match: "مطابقة الحضور",
    matchSub: "ربط أسماء الاجتماع بالمتطوعين",
    notifications: "الإشعارات",
    notificationsSub: "الإشعارات المرسلة حسب النوع، مع الرسائل غير المقروءة حالياً",
    emails: "الإيميلات",
    emailsSub: "رسائل التحقق واستعادة كلمة المرور المرسلة في الفترة",
    load: "حمل المنصة",
    loadSub: "عدد عمليات النظام المسجلة خلال الأيام المحددة",
    visitors: "إحصائيات زوار الموقع",
    visitorsSub: "الزوار المسجلون والضيوف، والأجهزة ومصادر الزيارة في المدة المختارة",
    rafiq: "رفيق بصمات",
    rafiqSub: "استخدام المساعد الذكي، والمستخدمون، والنماذج المستخدمة للرد",
    health: "حالة النظام",
    healthSub: "ملخص حالة الخدمات ونسبة العمليات التي سجّلت خطأ",
    comms: "التواصل",
    commsSub: "ملخص الرسائل والإشعارات",
    system: "سجل النظام",
    systemSub: "توزيع عمليات النظام حسب النتيجة"
  }
} as const;
