ALTER TABLE "analytics_daily"
ADD COLUMN IF NOT EXISTS "countries" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS "cities" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS "browsers" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS "operatingSystems" JSONB NOT NULL DEFAULT '{}';
