export const ADMIN_PERMISSIONS = [
  "MANAGE_ACTIVITIES",
  "MANAGE_REQUESTS",
  "MANAGE_USERS",
  "MANAGE_POSTS",
  "MANAGE_SPOTLIGHT",
  "MANAGE_MAGAZINE",
  "MANAGE_NOTIFICATIONS",
  "MANAGE_EMAILS",
  "MANAGE_MEETINGS"
] as const;

export type AdminPermission = (typeof ADMIN_PERMISSIONS)[number];
