export const ADMIN_PERMISSIONS = [
  "MANAGE_REPORTS",
  "MANAGE_LOGS",
  "MANAGE_POSTS",
  "MANAGE_SPOTLIGHT",
  "MANAGE_MAGAZINE",
  "MANAGE_REQUESTS",
  "MANAGE_ACTIVITIES",
  "MANAGE_MEETINGS",
  "MANAGE_EMAILS",
  "MANAGE_NOTIFICATIONS",
  "MANAGE_USERS"
] as const;

export type AdminPermission = (typeof ADMIN_PERMISSIONS)[number];
