export enum NotificationType {
  CERTIFICATE_ISSUED     = "CERTIFICATE_ISSUED",
  ANNOUNCEMENT           = "ANNOUNCEMENT",
  WELCOME                = "WELCOME",
  ACTIVITY_REMINDER      = "ACTIVITY_REMINDER",
  PARTICIPATION_APPROVED = "PARTICIPATION_APPROVED",
  PARTICIPATION_REJECTED = "PARTICIPATION_REJECTED",
  ACTIVITY_CANCELLED     = "ACTIVITY_CANCELLED",
  HOURS_MILESTONE        = "HOURS_MILESTONE",
  ACTIVITY_FULL          = "ACTIVITY_FULL",
}